sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t pandemic/scheduler-web .
  - docker run -d pandemic/scheduler-web
  - docker ps -a
  - docker run pandemic/scheduler-web /bin/bash -c "bundle exec rspec"

script:
  - bundle exec rspec

notifications:
  slack:
    secure: KFJ850yUDqI68AXfhhHkKv5ceE1vsyL6MhUxUn92hbAqGGPP28o2v3coBXHIwDXntze/+VadZfqThXk9utyTddLJ23DF2f1W2Hr5gpI/6IaHOUo/FkMqDEzo69Zh9m9UfwBGPf5wVayABOy4oDkruSAYNFAoOBTc3qDzeWq4uVg+dL8INBUCbL6OXxovco9HH2nyCNRr5UvV56uU+xXKC+twl3E28ttaV91pvzFggR45UpMPoio0I1P3fV5oOd7NsloMoWVnhsYGhggbk46Quvf+bEqOjcLGH7yBxsFMLFBFOgwhWC6M8bwb6Z6DjTJ0vRMAZdGu9HEq9DEz/27IrVINHAQLhjHgl8R/hoNVaDH1lNd5/HAWNPcxZR9Jgt+k/rXDZVLWOQSWby7tN0P9lXZvAL4WJLHRwtA1ueBI29VCxPbnGNj8S46q8IN5ksayyymrCQXK5sa3XaMCesKPrR2l9h83llYNd6AMTuX5IEIuX64jVPtq1Jbbmbp+qbpec3+uZlaLGSmgFmMD8YrYdlR69G9lbYbws3cktF4RwQbtO5pectEx9hUt2be2CNzNOn5wTssH0Nppw5YEB0Ibz1UNdJWcSMPTfYkJChemLtvahKfa8vHsyvai8ZeAN/zyKjGoTDCADWr1pRx2DKrkwn+rOGq9r/Q1HvVnWceUsVw=
