version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to docker hub...
      - docker login --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker build -t cp17scheduler_web .
      - docker tag cp17scheduler_web:latest tosto/cp17scheduler_web:latest
      - docker build -t cp17scheduler_sidekiq -f Dockerfile_sidekiq .
      - docker tag cp17scheduler_sidekiq:latest tosto/cp17scheduler_sidekiq:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push tosto/cp17scheduler_web:latest
      - docker push tosto/cp17scheduler_sidekiq:latest
      - mv aws/Dockerrun.aws.json .
artifacts:
  files:
    - 'Dockerrun.aws.json'
